name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! The issue will be auto-triaged to the appropriate organization.

  - type: dropdown
    id: organization
    attributes:
      label: Organization
      description: Which BlackRoad organization should implement this?
      options:
        - BlackRoad-OS (Core Infrastructure)
        - BlackRoad-AI (Intelligence Routing)
        - BlackRoad-Cloud (Edge Compute)
        - BlackRoad-Hardware (Pi Cluster / IoT)
        - BlackRoad-Security (Auth / Secrets)
        - BlackRoad-Labs (Experiments)
        - BlackRoad-Foundation (CRM / Finance)
        - BlackRoad-Ventures (Marketplace)
        - Blackbox-Enterprises (Enterprise)
        - BlackRoad-Media (Content)
        - BlackRoad-Studio (Design)
        - BlackRoad-Interactive (Metaverse)
        - BlackRoad-Education (Learning)
        - BlackRoad-Gov (Governance)
        - BlackRoad-Archive (Storage)
        - Not sure / Multiple orgs
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this feature work?
      placeholder: I would like to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other solutions have you considered?
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - Blocking my work
        - High - Very important
        - Medium - Would be nice to have
        - Low - Minor improvement
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any mockups, examples, or additional information
    validations:
      required: false
